# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  anchorpr.whitebox.cerberus.dev:
  lead0pr.whitebox.cerberus.dev:
  lead1pr.whitebox.cerberus.dev:
  communicatepr.whitebox.cerberus.dev:
  execute0pr.whitebox.cerberus.dev:
  execute1pr.whitebox.cerberus.dev:
  fallback0pr.whitebox.cerberus.dev:
  fallback1pr.whitebox.cerberus.dev:

networks:
  cerberusntw:

services:

  couchdb.anchorpr.whitebox:
    container_name: couchdb.anchorpr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=useranchorprwhitebox
      - COUCHDB_PASSWORD=passwordanchorprwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13044:5984
    networks:
      - cerberusntw

  anchorpr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: anchorpr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.anchorpr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=useranchorprwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordanchorprwhitebox
    depends_on:
      - couchdb.anchorpr.whitebox

  couchdb.lead0pr.whitebox:
    container_name: couchdb.lead0pr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=userlead0prwhitebox
      - COUCHDB_PASSWORD=passwordlead0prwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13048:5984
    networks:
      - cerberusntw

  lead0pr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: lead0pr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.lead0pr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=userlead0prwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordlead0prwhitebox
    depends_on:
      - couchdb.lead0pr.whitebox

  couchdb.lead1pr.whitebox:
    container_name: couchdb.lead1pr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=userlead1prwhitebox
      - COUCHDB_PASSWORD=passwordlead1prwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13052:5984
    networks:
      - cerberusntw

  lead1pr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: lead1pr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.lead1pr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=userlead1prwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordlead1prwhitebox
    depends_on:
      - couchdb.lead1pr.whitebox

  couchdb.communicatepr.whitebox:
    container_name: couchdb.communicatepr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=usercommunicateprwhitebox
      - COUCHDB_PASSWORD=passwordcommunicateprwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13056:5984
    networks:
      - cerberusntw

  communicatepr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: communicatepr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.communicatepr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=usercommunicateprwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordcommunicateprwhitebox
    depends_on:
      - couchdb.communicatepr.whitebox

  couchdb.execute0pr.whitebox:
    container_name: couchdb.execute0pr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=userexecute0prwhitebox
      - COUCHDB_PASSWORD=passwordexecute0prwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13060:5984
    networks:
      - cerberusntw

  execute0pr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: execute0pr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.execute0pr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=userexecute0prwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordexecute0prwhitebox
    depends_on:
      - couchdb.execute0pr.whitebox

  couchdb.execute1pr.whitebox:
    container_name: couchdb.execute1pr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=userexecute1prwhitebox
      - COUCHDB_PASSWORD=passwordexecute1prwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13064:5984
    networks:
      - cerberusntw

  execute1pr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: execute1pr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.execute1pr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=userexecute1prwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordexecute1prwhitebox
    depends_on:
      - couchdb.execute1pr.whitebox

  couchdb.fallback0pr.whitebox:
    container_name: couchdb.fallback0pr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=userfallback0prwhitebox
      - COUCHDB_PASSWORD=passwordfallback0prwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13068:5984
    networks:
      - cerberusntw

  fallback0pr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: fallback0pr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.fallback0pr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=userfallback0prwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordfallback0prwhitebox
    depends_on:
      - couchdb.fallback0pr.whitebox


  couchdb.fallback1pr.whitebox:
    container_name: couchdb.fallback1pr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=userfallback1prwhitebox
      - COUCHDB_PASSWORD=passwordfallback1prwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13072:5984
    networks:
      - cerberusntw

  fallback1pr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: fallback1pr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.fallback1pr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=userfallback1prwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordfallback1prwhitebox
    depends_on:
      - couchdb.fallback1pr.whitebox
